// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBpc8C6dntqW5RsUzBeJGIPrcwm8PuwrZo",
      authDomain: "ready-to-move-53059.firebaseapp.com",
      projectId: "ready-to-move-53059",
      storageBucket: "ready-to-move-53059.appspot.com",
      messagingSenderId: "744665051960",
      appId: "1:744665051960:web:caaa8ba132aa37e6d087cd",
      measurementId: "G-2HH1770KY7"
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: "AIzaSyBpc8C6dntqW5RsUzBeJGIPrcwm8PuwrZo",
      authDomain: "ready-to-move-53059.firebaseapp.com",
      projectId: "ready-to-move-53059",
      storageBucket: "ready-to-move-53059.appspot.com",
      messagingSenderId: "744665051960",
      appId: "1:744665051960:web:caaa8ba132aa37e6d087cd",
      measurementId: "G-2HH1770KY7"
  );
}
